### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by Cccooc** [YufiriaMazenta/Craftorithm#2]
[23:07:19 ERROR]: Could not pass event InventoryClickEvent to Craftorithm v1.2.1-20230323
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because the return value of "java.util.Map.get(Object)" is null
        at com.github.yufiriamazenta.craftorithm.menu.impl.recipe.RecipeDisplayMenuHolder.setShapedRecipeMenu(RecipeDisplayMenuHolder.java:107) ~[Craftorithm-1.2.1.jar:?]
        at com.github.yufiriamazenta.craftorithm.menu.impl.recipe.RecipeDisplayMenuHolder.<init>(RecipeDisplayMenuHolder.java:36) ~[Craftorithm-1.2.1.jar:?]
        at com.github.yufiriamazenta.craftorithm.menu.impl.recipe.RecipeListMenuHolder.lambda$resetIcons$3(RecipeListMenuHolder.java:79) ~[Craftorithm-1.2.1.jar:?]
        at com.github.yufiriamazenta.craftorithm.menu.bukkit.ItemDisplayIcon.onClick(ItemDisplayIcon.java:48) ~[Craftorithm-1.2.1.jar:?]
        at com.github.yufiriamazenta.craftorithm.menu.bukkit.BukkitMenuHandler.click(BukkitMenuHandler.java:34) ~[Craftorithm-1.2.1.jar:?]
        at com.github.yufiriamazenta.craftorithm.menu.bukkit.BukkitMenuDispatcher.onClickInv(BukkitMenuDispatcher.java:27) ~[Craftorithm-1.2.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor629.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2861) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by YufiriaMazenta** [comment]
已在1.3.0-dev3中修复
