### ISSUE TITLE
1.20.2创建一个配方报错了

### ISSUE THREAD

**Issue by BigAppleClass** [YufiriaMazenta/Craftorithm#4]
[09:45:52 INFO]: Naive_god issued server command: /craft reload
[09:45:52 INFO]: [Craftorithm] 加载配方123时出现错误
[09:45:52 WARN]: java.lang.IllegalArgumentException: No enum constant com.github.yufiriamazenta.craftorithm.recipe.RecipeType.COOKINGY
[09:45:52 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:293)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeType.valueOf(RecipeType.java:3)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.newRecipe(RecipeFactory.java:48)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadCraftorithmRecipes(RecipeManager.java:88)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadRecipes(RecipeManager.java:162)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.cmd.subcmd.ReloadCommand.reloadRecipes(ReloadCommand.java:51)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.cmd.subcmd.ReloadCommand.reloadPlugin(ReloadCommand.java:37)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.cmd.subcmd.ReloadCommand.onCommand(ReloadCommand.java:25)
[09:45:52 WARN]:        at Craftorithm-1.4.1.jar//com.github.yufiriamazenta.craftorithm.cmd.PluginCommand.onCommand(PluginCommand.java:41)
[09:45:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:45:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[09:45:52 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[09:45:52 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[09:45:52 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[09:45:52 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[09:45:52 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[09:45:52 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[09:45:52 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[09:45:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[09:45:52 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:45:52 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:45:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:45:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[09:45:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[09:45:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1410)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[09:45:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[09:45:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
>

![image](https://github.com/YufiriaMazenta/Craftorithm/assets/37060740/2ad958ec-dfe9-41b2-8961-7685d4ccb289)

**Comment by YufiriaMazenta** [comment]
因为还没兼容1.20.2,预计今晚会发兼容的版本
