### ISSUE TITLE
解析ni的全局节点若含有&会报错

### ISSUE THREAD

**Issue by postyizhan** [YufiriaMazenta/Craftorithm#57]
### Describe the bug | 描述你遇到的bug

解析ni的全局节点若含有&会报错

### Steps to reproduce the bug | 复现此Bug的步骤

# neigeitems

## GlobalSections
位置 `plugins\NeigeItems\GlobalSections\test.yml`
```
测试1: "&f&l1"
```

## Items
位置 `plugins\NeigeItems\Items\test.yml`
```
test1:
  material: stone
  lore:
  - '<测试1>'
  globalsections:
    - test.yml
```

# Craftorithm

位置 `plugins\Craftorithm\recipes\test.yml`

```
type: 'shaped'
multiple: true
shape:
  - - 'a  '
    - '   '
    - '   '

source:
  a: 'bedrock'

result: 'neige_items:test1'
```

### Server version | 服务器版本

[21:19:06 INFO]: Checking version, please wait...
[21:19:07 INFO]: Current: git-Leaf-"0354c1c" (MC: 1.20.4)*
You are 27 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous version: git-Paper-550 (MC: 1.19.4)

### Craftorithm Version | Craftorithm的版本

插件版本：1.9.3-20240411

### FULL server log | 完整服务器日志

```
[21:16:41 WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
[21:16:41 WARN]:  in 'reader', line 4, column 5:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:         ^
[21:16:41 WARN]: unexpected character found &(38)
[21:16:41 WARN]:  in 'reader', line 4, column 7:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:           ^
[21:16:41 WARN]:
[21:16:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.utils.ConfigUtils.loadFromString(ConfigUtils.kt:447)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.item.ItemGenerator.getItemStack(ItemGenerator.kt:437)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.manager.ItemManager.getItemStack(ItemManager.kt:177)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.manager.ItemManager.getItemStack(ItemManager.kt:120)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.item.impl.NeigeItemsItemProvider.getItem(NeigeItemsItemProvider.java:38)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.item.ItemManager.matchItem(ItemManager.java:83)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.getResultItem(RecipeFactory.java:378)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.newMultipleShapedRecipe(RecipeFactory.java:93)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.newRecipeRegistry(RecipeFactory.java:68)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadRecipeGroup(RecipeManager.java:134)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.lambda$loadRecipes$4(RecipeManager.java:124)
[21:16:41 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadRecipes(RecipeManager.java:124)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.reloadRecipeManager(RecipeManager.java:116)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.sub.ReloadCommand.reloadPlugin(ReloadCommand.java:39)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.sub.ReloadCommand.execute(ReloadCommand.java:26)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.crypticlib.command.ICommandHandler.onCommand(ICommandHandler.java:68)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.crypticlib.command.SubcommandHandler.onCommand(SubcommandHandler.java:45)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.PluginCommand.onCommand(PluginCommand.java:46)
[21:16:41 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:16:41 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:16:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1017)
[21:16:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:1002)
[21:16:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:547)
[21:16:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:495)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1520)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306)
[21:16:41 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[21:16:41 WARN]: Caused by: while scanning an anchor
[21:16:41 WARN]:  in 'reader', line 4, column 5:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:         ^
[21:16:41 WARN]: unexpected character found &(38)
[21:16:41 WARN]:  in 'reader', line 4, column 7:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:           ^
[21:16:41 WARN]:
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1510)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:968)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:401)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryValue.produce(ParserImpl.java:610)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:592)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:272)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
[21:16:41 WARN]:        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[21:16:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[21:16:41 WARN]:        ... 29 more[21:16:41 WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
[21:16:41 WARN]:  in 'reader', line 4, column 5:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:         ^
[21:16:41 WARN]: unexpected character found &(38)
[21:16:41 WARN]:  in 'reader', line 4, column 7:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:           ^
[21:16:41 WARN]:
[21:16:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.utils.ConfigUtils.loadFromString(ConfigUtils.kt:447)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.item.ItemGenerator.getItemStack(ItemGenerator.kt:437)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.manager.ItemManager.getItemStack(ItemManager.kt:177)
[21:16:41 WARN]:        at NeigeItems-1.17.5.jar//pers.neige.neigeitems.manager.ItemManager.getItemStack(ItemManager.kt:120)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.item.impl.NeigeItemsItemProvider.getItem(NeigeItemsItemProvider.java:38)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.item.ItemManager.matchItem(ItemManager.java:83)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.getResultItem(RecipeFactory.java:378)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.newMultipleShapedRecipe(RecipeFactory.java:93)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeFactory.newRecipeRegistry(RecipeFactory.java:68)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadRecipeGroup(RecipeManager.java:134)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.lambda$loadRecipes$4(RecipeManager.java:124)
[21:16:41 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.loadRecipes(RecipeManager.java:124)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.recipe.RecipeManager.reloadRecipeManager(RecipeManager.java:116)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.sub.ReloadCommand.reloadPlugin(ReloadCommand.java:39)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.sub.ReloadCommand.execute(ReloadCommand.java:26)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.crypticlib.command.ICommandHandler.onCommand(ICommandHandler.java:68)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.crypticlib.command.SubcommandHandler.onCommand(SubcommandHandler.java:45)
[21:16:41 WARN]:        at Craftorithm-1.9.3.jar//com.github.yufiriamazenta.craftorithm.cmd.PluginCommand.onCommand(PluginCommand.java:46)
[21:16:41 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:16:41 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:16:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1017)
[21:16:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:1002)
[21:16:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:547)
[21:16:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:495)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1520)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
[21:16:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306)
[21:16:41 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[21:16:41 WARN]: Caused by: while scanning an anchor
[21:16:41 WARN]:  in 'reader', line 4, column 5:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:         ^
[21:16:41 WARN]: unexpected character found &(38)
[21:16:41 WARN]:  in 'reader', line 4, column 7:
[21:16:41 WARN]:       - &f&l1
[21:16:41 WARN]:           ^
[21:16:41 WARN]:
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1510)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:968)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:401)
[21:16:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryValue.produce(ParserImpl.java:610)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:592)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
[21:16:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:272)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
[21:16:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
[21:16:41 WARN]:        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[21:16:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[21:16:41 WARN]:        ... 29 more
```

### Images | 相关图片

![db50be0ad7792756ca871ce1eb9c4ea9](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/b4a868c4-3ea1-4c3f-8e2f-3a3d74d6b749)

**Comment by YufiriaMazenta** [comment]
加上双引号或者单引号就不会报错了

**Comment by postyizhan** [comment]
> 加上双引号或者单引号就不会报错了 这是你的yaml格式有问题，和NI还有我的插件都没有关系

奥 原来是这样
