### ISSUE TITLE
Unsupported version: craftbukkit

### ISSUE THREAD

**Issue by RitaSister** [YufiriaMazenta/Craftorithm#59]
### Describe the bug | 描述你遇到的bug

while plugin is enabled I got error in ``RuntimeException``

### Steps to reproduce the bug | 复现此Bug的步骤

just start server on paper or folia 1.20.5/1.20.6 if the assembly has been assembled ``createMojmapBundlerJar``

### Server version | 服务器版本

This server is running Folia version git-Folia-"e11a709" (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: e11a709 on ver/1.20.6)
Error obtaining version information
Previous version: git-Folia-"46d3ab5" (MC: 1.20.4)

### Craftorithm Version | Craftorithm的版本

[15:27:55 INFO]: [Craftorithm] Plugin version: 1.9.4-dev2-20240510

### FULL server log | 完整服务器日志

[15:18:58] [Server thread/INFO]: [Craftorithm] Enabling Craftorithm v1.9.4-dev2-20240510
[15:19:00] [Server thread/INFO]: [Craftorithm] Error occurred while loading item example_item:example_item.
[15:19:00] [Server thread/WARN]: java.lang.RuntimeException: Unsupported version: craftbukkit
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.crypticlib.nms.nbt.NbtFactory.lambda$emptyNbtCompound$2(NbtFactory.java:90)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.crypticlib.nms.nbt.NbtFactory.emptyNbtCompound(NbtFactory.java:91)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.crypticlib.nms.item.ItemFactory.item(ItemFactory.java:96)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.impl.CraftorithmItemProvider.loadItem(CraftorithmItemProvider.java:108)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.impl.CraftorithmItemProvider.loadItems(CraftorithmItemProvider.java:101)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.impl.CraftorithmItemProvider.<init>(CraftorithmItemProvider.java:35)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.impl.CraftorithmItemProvider.<clinit>(CraftorithmItemProvider.java:26)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.ItemManager.regDefaultProviders(ItemManager.java:45)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.item.ItemManager.loadItemManager(ItemManager.java:40)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.Craftorithm.enable(Craftorithm.java:30)
[15:19:00] [Server thread/WARN]: 	at Craftorithm-1.9.4-dev2.jar//com.github.yufiriamazenta.craftorithm.crypticlib.BukkitPlugin.onEnable(BukkitPlugin.java:118)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[15:19:00] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:19:00] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:645)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:557)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:725)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:469)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:354)
[15:19:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[15:19:00] [Server thread/INFO]: [Craftorithm] Found Vault, hooked successfully.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin PlayerPoints not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin NeigeItems not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin ItemsAdder not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin Oraxen not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin MMOItems not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin MythicMobs not found.
[15:19:00] [Server thread/INFO]: [Craftorithm] Plugin loaded successfully.

**Comment by YufiriaMazenta** [comment]
This is a problem caused by paper. This problem does not occur on spigot. Unless paper provides a method to obtain the current nms version, it cannot be repaired.

**Comment by YufiriaMazenta** [comment]
I will also try to solve it in other ways

**Comment by RitaSister** [comment]
> I will also try to solve it in other ways

I'm try resolve this problem with other plugin for myself on 1.20.6 folia, thanks

**Comment by RitaSister** [comment]
I'm compile your plugin from dev branch and it is work, but that mistake has left, so I think is to easy fix

**Comment by YufiriaMazenta** [comment]
It has been fixed and will be updated in the next release.
