### ISSUE TITLE
Items with an NBT's

### ISSUE THREAD

**Issue by Netherhunter945** [YufiriaMazenta/Craftorithm#66]
### Describe the bug | 描述你遇到的bug

Items with NBT data (or at least a custom name) cannot be used for the ouput of a crafted item

### Steps to reproduce the bug | 复现此Bug的步骤

Get an item with a custom name or with enchant glint or any custom NBT data and try put the item as a result of a craft, smelt or whatever.

### Server version | 服务器版本

This server is running Paper version 1.21-66-master@99ae7bb (2024-07-14T13:40:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-49-b0ef3ca (MC: 1.21)

### Craftorithm Version | Craftorithm的版本

[Craftorithm] Plugin version: 1.10.4-20240625

### FULL server log | 完整服务器日志

[16:02:22 ERROR]: Could not pass event InventoryClickEvent to Craftorithm v1.10.4-20240625
java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.api.volatilecode.handlers.VolatileItemHandler.getNBTData(org.bukkit.inventory.ItemStack)" because the return value of "io.lumine.mythic.api.volatilecode.VolatileCodeHandler.getItemHandler()" is null
        at MythicMobs-5.6.2.jar/io.lumine.mythic.core.items.ItemExecutor.isMythicItem(ItemExecutor.java:153) ~[MythicMobs-5.6.2.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.item.impl.MythicMobsItemProvider.getItemName(MythicMobsItemProvider.java:26) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.item.ItemManager.matchItemName(ItemManager.java:102) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.util.ItemUtils.matchItemNameOrCreate(ItemUtils.java:84) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.menu.creator.CraftingRecipeCreator.lambda$new$1(CraftingRecipeCreator.java:53) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.crypticlib.ui.display.Icon.onClick(Icon.java:109) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.crypticlib.ui.menu.StoredMenu.onClick(StoredMenu.java:52) ~[Craftorithm-1.10.4.jar:?]
        at Craftorithm-1.10.4.jar/com.github.yufiriamazenta.craftorithm.crypticlib.ui.handler.MenuHandler.onClickMenu(MenuHandler.java:28) ~[Craftorithm-1.10.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Netherhunter945** [comment]
I know it isn't the full server log but I'm preloading the world atm so chunky is spamming the logs

**Comment by YufiriaMazenta** [comment]
I think this is an internal problem of MythicMobs. I just used its API. You can ask the developers of MythicMobs what is going on.

**Comment by Netherhunter945** [comment]
Oh. Probably because the server is 1.21
