### ISSUE TITLE
 Could not pass event InventoryCloseEvent to Craftorithm v1.10.6-20240728

### ISSUE THREAD

**Issue by ivan100-ivoop** [YufiriaMazenta/Craftorithm#69]
### Describe the bug | 描述你遇到的bug

on player open invertory or chest, etc

### Steps to reproduce the bug | 复现此Bug的步骤

on i upload it and start server start give this error

### Server version | 服务器版本

[10:13:46 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Craftorithm Version | Craftorithm的版本

Plugin version: 1.10.6-20240728

### FULL server log | 完整服务器日志

[10:10:59 ERROR]: Could not pass event InventoryCloseEvent to Craftorithm v1.10.6-20240728
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at Craftorithm-1.10.6.jar/com.github.yufiriamazenta.craftorithm.crypticlib.ui.handler.MenuHandler.onCloseMenu(MenuHandler.java:47) ~[Craftorithm-1.10.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor555.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1624) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2874) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2867) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:33) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Images | 相关图片

![image](https://github.com/user-attachments/assets/724bd96f-9392-4e1f-bd9a-31b11c3c1513)
![image](https://github.com/user-attachments/assets/3614d2f4-6253-4bc0-bbbb-f0455ce07eee)

**Comment by YufiriaMazenta** [comment]
![image](https://github.com/user-attachments/assets/4e94612d-ba27-48f9-a9d4-214cf45c9f2d)
![image](https://github.com/user-attachments/assets/5ae2a77d-3edb-4c1d-b719-df7d0ca23860)

**Comment by ivan100-ivoop** [comment]
![image](https://github.com/user-attachments/assets/06dcb085-a446-4e2e-86f9-a1a75a8975f9)
this is hosting configuration.

**Comment by ivan100-ivoop** [comment]
here plugins mybe some plugin make sometihing ?
![image](https://github.com/user-attachments/assets/0892d5bc-f049-4c0d-91ec-0a495dd5f1a8)

**Comment by YufiriaMazenta** [comment]
You need to remove -Dpaper.disable-plugin-rewriting=true to let paper remap the plugin to solve this problem

**Comment by ivan100-ivoop** [comment]
oh this will be hard this is auto command from hosting but thanks for help i will text them

**Comment by YufiriaMazenta** [comment]
1.10.8 fixed this problem
