### ISSUE TITLE
Error with Evenmorefishing

### ISSUE THREAD

**Issue by asygamesperson** [YufiriaMazenta/Craftorithm#77]
### Describe the bug | 描述你遇到的bug

I can't use items from Evenmorefishing plugin

### Steps to reproduce the bug | 复现此Bug的步骤

Use a bait

### Server version | 服务器版本

1.21.1 folia

### Craftorithm Version | Craftorithm的版本

Plugin version: 1.10.10-20240913

### FULL server log | 完整服务器日志

[23:57:37 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[23:57:37 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitNBTManager.newApplyLore(BaitNBTManager.java:366)
[23:57:37 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitNBTManager.applyBaitedRodNBT(BaitNBTManager.java:205)
[23:57:37 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitListener.onClickEvent(BaitListener.java:65)
[23:57:37 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source)
[23:57:37 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:57:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:57:37 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:535)
[23:57:37 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyInventoryClick(OtherPluginsListenerProxy.java:486)
[23:57:37 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyNormalInventoryClick(OtherPluginsListenerProxy.java:460)
[23:57:37 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor847.execute(Unknown Source)
[23:57:37 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:57:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:57:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:57:37 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[23:57:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[23:57:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[23:57:37 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3303)
[23:57:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[23:57:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[23:57:37 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:58)
[23:57:37 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:86)
[23:57:37 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181)
[23:57:37 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711)
[23:57:37 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[23:57:37 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418)
[23:57:37 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540)
[23:57:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:57:40 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[23:57:40 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitNBTManager.newApplyLore(BaitNBTManager.java:366)
[23:57:40 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitNBTManager.applyBaitedRodNBT(BaitNBTManager.java:205)
[23:57:40 WARN]:        at even-more-fish-1.7.4-130.jar//com.oheers.fish.baits.BaitListener.onClickEvent(BaitListener.java:65)
[23:57:40 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source)
[23:57:40 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:57:40 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:57:40 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:535)
[23:57:40 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyInventoryClick(OtherPluginsListenerProxy.java:486)
[23:57:40 WARN]:        at Craftorithm-1.10.10.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyNormalInventoryClick(OtherPluginsListenerProxy.java:460)
[23:57:40 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor847.execute(Unknown Source)
[23:57:40 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:57:40 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:57:40 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:57:40 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[23:57:40 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[23:57:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[23:57:40 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3303)
[23:57:40 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[23:57:40 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[23:57:40 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:58)
[23:57:40 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:86)
[23:57:40 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181)
[23:57:40 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711)
[23:57:40 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[23:57:40 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418)
[23:57:40 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540)
[23:57:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by YufiriaMazenta** [comment]
This is not my problem, I just called his method, please give feedback to the author of evenmorefish
