### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Tareyu** [YufiriaMazenta/Craftorithm#78]
### Describe the bug | 描述你遇到的bug

Got error spaming my console when i put ingredients in crafting table and when i take the result
I use itemsadders items

### Steps to reproduce the bug | 复现此Bug的步骤

Just make what i said over

### Server version | 服务器版本

Paper 1.21.1-119

### Craftorithm Version | Craftorithm的版本

1.10.11-20241012

### FULL server log | 完整服务器日志

[01:29:06 WARN]: java.lang.NullPointerException: Cannot invoke "itemsadder.m.mw.a(org.bukkit.inventory.CraftingInventory)" because "<local8>" is null
[01:29:06 WARN]:        at ItemsAdder_4.0.2-beta-release-12.jar//itemsadder.m.my.a(SourceFile:426)
[01:29:06 WARN]:        at ItemsAdder_4.0.2-beta-release-12.jar//itemsadder.m.my.a(SourceFile:330)
[01:29:06 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44)
[01:29:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:535)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyPrepareItemCraft(OtherPluginsListenerProxy.java:156)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyMonitorPrepareItemCraft(OtherPluginsListenerProxy.java:139)
[01:29:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor952.execute(Unknown Source)
[01:29:06 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:29:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[01:29:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:29:06 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:29:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[01:29:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:29:06 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1454)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:98)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:110)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:85)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:72)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:84)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:109)
[01:29:06 WARN]:        at net.minecraft.world.inventory.TransientCraftingContainer.removeItem(TransientCraftingContainer.java:138)
[01:29:06 WARN]:        at net.minecraft.world.inventory.Slot.remove(Slot.java:88)
[01:29:06 WARN]:        at net.minecraft.world.inventory.Slot.tryRemove(Slot.java:106)
[01:29:06 WARN]:        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:561)
[01:29:06 WARN]:        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382)
[01:29:06 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3232)
[01:29:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[01:29:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[01:29:06 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[01:29:06 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:29:06 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[01:29:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[01:29:06 WARN]: java.lang.NullPointerException: Cannot invoke "itemsadder.m.mw.a(org.bukkit.inventory.CraftingInventory)" because "<local8>" is null
[01:29:06 WARN]:        at ItemsAdder_4.0.2-beta-release-12.jar//itemsadder.m.my.a(SourceFile:426)
[01:29:06 WARN]:        at ItemsAdder_4.0.2-beta-release-12.jar//itemsadder.m.my.a(SourceFile:330)
[01:29:06 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44)
[01:29:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:535)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyPrepareItemCraft(OtherPluginsListenerProxy.java:156)
[01:29:06 WARN]:        at Craftorithm-1.10.11.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyMonitorPrepareItemCraft(OtherPluginsListenerProxy.java:139)
[01:29:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor952.execute(Unknown Source)
[01:29:06 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:29:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[01:29:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:29:06 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:29:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[01:29:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:29:06 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1454)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:98)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:110)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:85)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:72)
[01:29:06 WARN]:        at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:84)
[01:29:06 WARN]:        at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:109)
[01:29:06 WARN]:        at net.minecraft.world.inventory.TransientCraftingContainer.setItem(TransientCraftingContainer.java:147)
[01:29:06 WARN]:        at net.minecraft.world.inventory.Slot.set(Slot.java:66)
[01:29:06 WARN]:        at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:62)
[01:29:06 WARN]:        at net.minecraft.world.inventory.Slot.tryRemove(Slot.java:111)
[01:29:06 WARN]:        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:561)
[01:29:06 WARN]:        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382)
[01:29:06 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3232)
[01:29:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[01:29:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[01:29:06 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[01:29:06 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:29:06 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[01:29:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[01:29:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[01:29:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by YufiriaMazenta** [comment]
This is a problem with ItemsAdder, please report it to lonedev
